from pathlib import Path
from datetime import timedelta, datetime, timezone
from typing import List, Union

from jinja2 import Environment, BaseLoader

from forensixd.core.models import SessionLog, Artifact
from forensixd.core.exceptions import WriteError

__all__ = ["ReportWriter"]

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<title>Forensic Report — {{ session.case.case_number }}</title>
<style>
body{font-family:Arial,sans-serif;font-size:13px;margin:2cm;color:#111}
h1{font-size:18px;border-bottom:2px solid #333;padding-bottom:6px}
h2{font-size:14px;margin-top:24px;color:#333}
table{border-collapse:collapse;width:100%;margin-bottom:16px}
th{background:#333;color:#fff;padding:6px 8px;text-align:left;font-size:12px}
td{border:1px solid #ccc;padding:5px 8px;font-size:12px;word-break:break-all}
tr:nth-child(even){background:#f9f9f9}
.warn{background:#fff3cd;border:1px solid #ffc107;padding:8px;margin-bottom:16px}
code{font-size:11px}
</style></head><body>
<h1>Forensic Examination Report</h1>
<div class="warn"><strong>OFFICIAL DOCUMENT.</strong>
Court Order: {{ session.case.court_order_ref }} | Examiner: {{ session.case.examiner_id }}</div>
<h2>Case Information</h2>
<table>
<tr><th>Case Number</th><td>{{ session.case.case_number }}</td></tr>
<tr><th>Court Order Ref</th><td>{{ session.case.court_order_ref }}</td></tr>
<tr><th>Examiner ID</th><td>{{ session.case.examiner_id }}</td></tr>
<tr><th>Jurisdiction</th><td>{{ session.case.jurisdiction }}</td></tr>
<tr><th>Platform</th><td>{{ session.case.device.platform.value }}</td></tr>
<tr><th>Session Started</th><td>{{ session.started_at }}</td></tr>
<tr><th>Total Artifacts</th><td>{{ artifacts | length }}</td></tr>
<tr><th>Root Hash</th><td><code>{{ session.root_hash }}</code></td></tr>
</table>
<h2>Hash Verification Table</h2>
<table>
<tr><th>Artifact ID</th><th>Path</th><th>MD5</th><th>SHA-256</th><th>Type</th></tr>
{% for a in artifacts %}
<tr><td><code>{{ a.artifact_id[:8] }}...</code></td><td>{{ a.source_path }}</td>
<td><code>{{ a.hashes.md5 }}</code></td><td><code>{{ a.hashes.sha256[:24] }}...</code></td>
<td>{{ a.artifact_type.value }}</td></tr>{% endfor %}
</table>
<h2>Acquisition Timeline</h2>
<table>
<tr><th>Timestamp (UTC)</th><th>App</th><th>Type</th><th>Path</th></tr>
{% for a in artifacts | sort(attribute='acquired_at') %}
<tr><td>{{ a.acquired_at.strftime('%Y-%m-%d %H:%M:%S') }}</td>
<td>{{ a.source_app }}</td><td>{{ a.artifact_type.value }}</td>
<td>{{ a.source_path }}</td></tr>{% endfor %}
</table>
<p style="font-size:11px;color:#666;margin-top:32px">Generated by forensixd v0.1.0 on {{ generated_at }}</p>
</body></html>"""


class ReportWriter:
    """Writer for generating HTML and PDF forensic reports."""

    @staticmethod
    def generate_html(
        session: SessionLog, artifacts: List[Artifact], output_path: Union[str, Path]
    ) -> Path:
        """
        Generate an HTML forensic report.

        Args:
            session: The forensic session log containing case metadata.
            artifacts: The list of artifacts to include in the report.
            output_path: The path where the HTML report will be written.

        Returns:
            The path to the generated HTML file.

        Raises:
            WriteError: If the HTML report cannot be written.
        """
        output = Path(output_path)
        env = Environment(loader=BaseLoader())
        template = env.from_string(HTML_TEMPLATE)
        html_content = template.render(
            session=session,
            artifacts=artifacts,
            generated_at=datetime.now(timezone(timedelta(hours=5, minutes=30))).isoformat(),
        )

        try:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(html_content, encoding="utf-8")
        except Exception as e:
            raise WriteError(f"Failed to write HTML report to {output}: {e}") from e

        return output

    @staticmethod
    def generate_pdf(html_path: Union[str, Path], output_path: Union[str, Path]) -> Path:
        """
        Convert an existing HTML forensic report to a PDF.

        Args:
            html_path: The path to the source HTML file.
            output_path: The path where the PDF report will be written.

        Returns:
            The path to the generated PDF file.

        Raises:
            WriteError: If the PDF report cannot be generated or weasyprint is missing.
        """
        try:
            from xhtml2pdf import pisa
        except ImportError:
            raise WriteError("Run: pip install xhtml2pdf")

        html_p = Path(html_path)
        out_p = Path(output_path)

        try:
            out_p.parent.mkdir(parents=True, exist_ok=True)
            with open(html_p, "r", encoding="utf-8") as source_html:
                with open(out_p, "w+b") as result_file:
                    pisa_status = pisa.CreatePDF(source_html, dest=result_file)
            if pisa_status.err:
                raise Exception("xhtml2pdf rendering error")
        except Exception as e:
            raise WriteError(f"Failed to generate PDF at {out_p}: {e}") from e

        return out_p
